object Form2: TForm2
  Left = 264
  Top = 134
  BorderIcons = [biSystemMenu, biMinimize]
  BorderStyle = bsSingle
  Caption = 'Kendali Motor'
  ClientHeight = 315
  ClientWidth = 419
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = True
  PixelsPerInch = 96
  TextHeight = 13
  object AdvSmoothButton1: TAdvSmoothButton
    Left = 8
    Top = 0
    Width = 120
    Height = 35
    Status.Caption = '0'
    Status.Appearance.Fill.Color = clRed
    Status.Appearance.Fill.ColorMirror = clNone
    Status.Appearance.Fill.ColorMirrorTo = clNone
    Status.Appearance.Fill.GradientType = gtSolid
    Status.Appearance.Fill.GradientMirrorType = gtSolid
    Status.Appearance.Fill.BorderColor = clGray
    Status.Appearance.Fill.Rounding = 0
    Status.Appearance.Fill.ShadowOffset = 0
    Status.Appearance.Fill.Glow = gmNone
    Status.Appearance.Font.Charset = DEFAULT_CHARSET
    Status.Appearance.Font.Color = clWhite
    Status.Appearance.Font.Height = -11
    Status.Appearance.Font.Name = 'Tahoma'
    Status.Appearance.Font.Style = []
    Caption = 'Open USB Device'
    Color = 15784647
    TabOrder = 0
    Version = '2.0.2.0'
    OnClick = Button3Click
  end
  object AdvSmoothTabPager1: TAdvSmoothTabPager
    Left = 8
    Top = 40
    Width = 401
    Height = 250
    Fill.Color = 16643823
    Fill.ColorTo = 15784647
    Fill.ColorMirror = clNone
    Fill.ColorMirrorTo = clNone
    Fill.GradientType = gtVertical
    Fill.GradientMirrorType = gtVertical
    Fill.BorderColor = 13087391
    Fill.Rounding = 0
    Fill.ShadowOffset = 0
    Fill.Glow = gmNone
    Transparent = False
    ActivePage = AdvSmoothTabPage1
    TabPosition = tpTopLeft
    TabSettings.StartMargin = 4
    TabReorder = False
    TabOrder = 1
    object AdvSmoothTabPager11: TAdvSmoothTabPage
      Left = 1
      Top = 26
      Width = 399
      Height = 222
      Caption = 'Motor DC'
      PageAppearance.Color = 16643823
      PageAppearance.ColorTo = 15784647
      PageAppearance.ColorMirror = clNone
      PageAppearance.ColorMirrorTo = clNone
      PageAppearance.GradientType = gtVertical
      PageAppearance.GradientMirrorType = gtVertical
      PageAppearance.BorderColor = 13087391
      PageAppearance.Rounding = 0
      PageAppearance.ShadowOffset = 0
      PageAppearance.Glow = gmNone
      TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
      TabAppearance.Appearance.Font.Color = clWindowText
      TabAppearance.Appearance.Font.Height = -11
      TabAppearance.Appearance.Font.Name = 'Tahoma'
      TabAppearance.Appearance.Font.Style = []
      TabAppearance.Status.Caption = '0'
      TabAppearance.Status.Appearance.Fill.Color = clRed
      TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
      TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
      TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
      TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
      TabAppearance.Status.Appearance.Fill.BorderColor = clGray
      TabAppearance.Status.Appearance.Fill.Rounding = 0
      TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
      TabAppearance.Status.Appearance.Fill.Glow = gmNone
      TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
      TabAppearance.Status.Appearance.Font.Color = clWhite
      TabAppearance.Status.Appearance.Font.Height = -11
      TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
      TabAppearance.Status.Appearance.Font.Style = []
      TabAppearance.BevelColor = 16644856
      TabAppearance.BevelColorDown = 13087391
      TabAppearance.BevelColorSelected = 13087391
      TabAppearance.BevelColorHot = 12236209
      TabAppearance.BevelColorDisabled = 16644856
      TabAppearance.Color = 16644856
      TabAppearance.ColorDown = 15784647
      TabAppearance.ColorSelected = 15784647
      TabAppearance.ColorHot = 15920100
      TabAppearance.ColorDisabled = 15921906
      object AdvSmoothGauge1: TAdvSmoothGauge
        Left = 176
        Top = 8
        Width = 202
        Height = 202
        MaximumValue = 255.000000000000000000
        Digit.Color = 7953476
        Digit.BackGroundColor = 7953476
        OuterCircle.Color = 13087391
        OuterCircle.Width = 0.030000000000000000
        InnerCircle.Color = 15389631
        OuterRim.Width = 2
        Needle.Color = 9841920
        Needle.ShineColor = 15389631
        Needle.OuterCenterColor = 14598569
        Needle.InnerCenterColor = 16643565
        Needle.InnerCenterColorTo = clGray
        Arc.Color = 14598569
        Arc.Width = 0.030000000000000000
        Arc.Threshold.Color = 16643565
        Arc.Threshold.Center = 25.000000000000000000
        Arc.Threshold.EndValue = 100.000000000000000000
        DivisionCount = 5
        SubDivisionCount = 5
        DivisionColor = 5978398
        SubDivisionColor = 5978398
        DialText = 'PWM'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = 9841920
        Font.Height = -19
        Font.Name = 'Tahoma'
        Font.Style = []
        ValueFont.Charset = DEFAULT_CHARSET
        ValueFont.Color = 9841920
        ValueFont.Height = -15
        ValueFont.Name = 'Tahoma'
        ValueFont.Style = []
        ValueFormat = '000'
        Version = '2.2.0.0'
        Sections = <>
        OnChange = AdvSmoothGauge1Change
        ExtraNeedles = <>
        TabOrder = 0
      end
      object RadioGroup1: TRadioGroup
        Left = 8
        Top = 8
        Width = 161
        Height = 97
        Caption = 'Arah Puataran '
        ItemIndex = 1
        Items.Strings = (
          'Kiri'
          'Stop'
          'Kanan')
        TabOrder = 1
        OnClick = RadioGroup1Click
      end
    end
    object AdvSmoothTabPager12: TAdvSmoothTabPage
      Left = 1
      Top = 26
      Width = 399
      Height = 222
      Caption = 'Motor Stepper'
      PageAppearance.Color = 16643823
      PageAppearance.ColorTo = 15784647
      PageAppearance.ColorMirror = clNone
      PageAppearance.ColorMirrorTo = clNone
      PageAppearance.GradientType = gtVertical
      PageAppearance.GradientMirrorType = gtVertical
      PageAppearance.BorderColor = 13087391
      PageAppearance.Rounding = 0
      PageAppearance.ShadowOffset = 0
      PageAppearance.Glow = gmNone
      TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
      TabAppearance.Appearance.Font.Color = clWindowText
      TabAppearance.Appearance.Font.Height = -11
      TabAppearance.Appearance.Font.Name = 'Tahoma'
      TabAppearance.Appearance.Font.Style = []
      TabAppearance.Status.Caption = '0'
      TabAppearance.Status.Appearance.Fill.Color = clRed
      TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
      TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
      TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
      TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
      TabAppearance.Status.Appearance.Fill.BorderColor = clGray
      TabAppearance.Status.Appearance.Fill.Rounding = 0
      TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
      TabAppearance.Status.Appearance.Fill.Glow = gmNone
      TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
      TabAppearance.Status.Appearance.Font.Color = clWhite
      TabAppearance.Status.Appearance.Font.Height = -11
      TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
      TabAppearance.Status.Appearance.Font.Style = []
      TabAppearance.BevelColor = 16644856
      TabAppearance.BevelColorDown = 13087391
      TabAppearance.BevelColorSelected = 13087391
      TabAppearance.BevelColorHot = 12236209
      TabAppearance.BevelColorDisabled = 16644856
      TabAppearance.Color = 16644856
      TabAppearance.ColorDown = 15784647
      TabAppearance.ColorSelected = 15784647
      TabAppearance.ColorHot = 15920100
      TabAppearance.ColorDisabled = 15921906
      object AdvSmoothLabel1: TAdvSmoothLabel
        Left = 8
        Top = 24
        Width = 113
        Height = 17
        Fill.ColorMirror = clNone
        Fill.ColorMirrorTo = clNone
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtSolid
        Fill.BorderColor = clNone
        Fill.Rounding = 0
        Fill.ShadowOffset = 0
        Fill.Glow = gmNone
        Caption.Text = 'Arah Putaran'
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -13
        Caption.Font.Name = 'Arial'
        Caption.Font.Style = []
        Caption.ColorEnd = clNavy
        CaptionShadow.Text = 'Arah Putaran'
        CaptionShadow.Font.Charset = DEFAULT_CHARSET
        CaptionShadow.Font.Color = clWindowText
        CaptionShadow.Font.Height = -27
        CaptionShadow.Font.Name = 'Tahoma'
        CaptionShadow.Font.Style = []
        Version = '1.6.0.2'
      end
      object AdvSmoothLabel2: TAdvSmoothLabel
        Left = 8
        Top = 48
        Width = 113
        Height = 17
        Fill.ColorMirror = clNone
        Fill.ColorMirrorTo = clNone
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtSolid
        Fill.BorderColor = clNone
        Fill.Rounding = 0
        Fill.ShadowOffset = 0
        Fill.Glow = gmNone
        Caption.Text = 'Jumlah Step'
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -13
        Caption.Font.Name = 'Arial'
        Caption.Font.Style = []
        Caption.ColorEnd = clNavy
        CaptionShadow.Text = 'Jumlah Step'
        CaptionShadow.Font.Charset = DEFAULT_CHARSET
        CaptionShadow.Font.Color = clWindowText
        CaptionShadow.Font.Height = -27
        CaptionShadow.Font.Name = 'Tahoma'
        CaptionShadow.Font.Style = []
        Version = '1.6.0.2'
      end
      object AdvSmoothLabel3: TAdvSmoothLabel
        Left = 8
        Top = 136
        Width = 377
        Height = 17
        Fill.ColorMirror = clNone
        Fill.ColorMirrorTo = clNone
        Fill.GradientType = gtVertical
        Fill.GradientMirrorType = gtSolid
        Fill.BorderColor = clNone
        Fill.Rounding = 0
        Fill.ShadowOffset = 0
        Fill.Glow = gmNone
        Caption.Text = 'Kecepatan = 0,005ms/step'
        Caption.Location = plTopLeft
        Caption.Font.Charset = DEFAULT_CHARSET
        Caption.Font.Color = clWindowText
        Caption.Font.Height = -13
        Caption.Font.Name = 'Arial'
        Caption.Font.Style = []
        Caption.ColorEnd = clNavy
        CaptionShadow.Text = 'Kecepatan = 0,005ms/step'
        CaptionShadow.Font.Charset = DEFAULT_CHARSET
        CaptionShadow.Font.Color = clWindowText
        CaptionShadow.Font.Height = -27
        CaptionShadow.Font.Name = 'Tahoma'
        CaptionShadow.Font.Style = []
        Version = '1.6.0.2'
      end
      object AdvSmoothButton2: TAdvSmoothButton
        Left = 16
        Top = 72
        Width = 120
        Height = 35
        Status.Caption = '0'
        Status.Appearance.Fill.Color = clRed
        Status.Appearance.Fill.ColorMirror = clNone
        Status.Appearance.Fill.ColorMirrorTo = clNone
        Status.Appearance.Fill.GradientType = gtSolid
        Status.Appearance.Fill.GradientMirrorType = gtSolid
        Status.Appearance.Fill.BorderColor = clGray
        Status.Appearance.Fill.Rounding = 0
        Status.Appearance.Fill.ShadowOffset = 0
        Status.Appearance.Fill.Glow = gmNone
        Status.Appearance.Font.Charset = DEFAULT_CHARSET
        Status.Appearance.Font.Color = clWhite
        Status.Appearance.Font.Height = -11
        Status.Appearance.Font.Name = 'Tahoma'
        Status.Appearance.Font.Style = []
        Caption = 'Eksekusi'
        Color = 15784647
        TabOrder = 0
        Version = '2.0.2.0'
        OnClick = Buttonx1Click
      end
      object TrackBar1: TTrackBar
        Left = 6
        Top = 161
        Width = 387
        Height = 45
        Max = 50000
        Min = 50
        Position = 50
        TabOrder = 1
        OnChange = TrackBar1Change
      end
      object ComboBox1: TComboBox
        Left = 120
        Top = 17
        Width = 65
        Height = 21
        ItemHeight = 13
        ItemIndex = 0
        TabOrder = 2
        Text = 'Kanan'
        Items.Strings = (
          'Kanan'
          'Kiri')
      end
      object Edit1: TEdit
        Left = 120
        Top = 41
        Width = 49
        Height = 21
        TabOrder = 3
        Text = '0'
      end
      object UpDown1: TUpDown
        Left = 169
        Top = 41
        Width = 16
        Height = 21
        Associate = Edit1
        Max = 1000
        TabOrder = 4
      end
    end
    object AdvSmoothTabPage1: TAdvSmoothTabPage
      Left = 1
      Top = 26
      Width = 399
      Height = 222
      Caption = 'AdvSmoothTabPage1'
      PageAppearance.Color = 16643823
      PageAppearance.ColorTo = 15784647
      PageAppearance.ColorMirror = clNone
      PageAppearance.ColorMirrorTo = clNone
      PageAppearance.GradientType = gtVertical
      PageAppearance.GradientMirrorType = gtVertical
      PageAppearance.BorderColor = 13087391
      PageAppearance.Rounding = 0
      PageAppearance.ShadowOffset = 0
      PageAppearance.Glow = gmNone
      TabAppearance.Appearance.Font.Charset = DEFAULT_CHARSET
      TabAppearance.Appearance.Font.Color = clWindowText
      TabAppearance.Appearance.Font.Height = -11
      TabAppearance.Appearance.Font.Name = 'Tahoma'
      TabAppearance.Appearance.Font.Style = []
      TabAppearance.Status.Caption = '0'
      TabAppearance.Status.Appearance.Fill.Color = clRed
      TabAppearance.Status.Appearance.Fill.ColorMirror = clNone
      TabAppearance.Status.Appearance.Fill.ColorMirrorTo = clNone
      TabAppearance.Status.Appearance.Fill.GradientType = gtSolid
      TabAppearance.Status.Appearance.Fill.GradientMirrorType = gtSolid
      TabAppearance.Status.Appearance.Fill.BorderColor = clGray
      TabAppearance.Status.Appearance.Fill.Rounding = 0
      TabAppearance.Status.Appearance.Fill.ShadowOffset = 0
      TabAppearance.Status.Appearance.Fill.Glow = gmNone
      TabAppearance.Status.Appearance.Font.Charset = DEFAULT_CHARSET
      TabAppearance.Status.Appearance.Font.Color = clWhite
      TabAppearance.Status.Appearance.Font.Height = -11
      TabAppearance.Status.Appearance.Font.Name = 'Tahoma'
      TabAppearance.Status.Appearance.Font.Style = []
      TabAppearance.BevelColor = 16644856
      TabAppearance.BevelColorDown = 13087391
      TabAppearance.BevelColorSelected = 13087391
      TabAppearance.BevelColorHot = 12236209
      TabAppearance.BevelColorDisabled = 16644856
      TabAppearance.Color = 16644856
      TabAppearance.ColorDown = 15784647
      TabAppearance.ColorSelected = 15784647
      TabAppearance.ColorHot = 15920100
      TabAppearance.ColorDisabled = 15921906
      object Edit2: TEdit
        Left = 16
        Top = 16
        Width = 121
        Height = 21
        TabOrder = 0
        Text = '0'
      end
      object Button1: TButton
        Left = 144
        Top = 16
        Width = 75
        Height = 25
        Caption = 'Button1'
        TabOrder = 1
        OnClick = Button1Click
      end
    end
  end
  object AdvSmoothButton3: TAdvSmoothButton
    Left = 288
    Top = 0
    Width = 120
    Height = 35
    Status.Caption = '0'
    Status.Appearance.Fill.Color = clRed
    Status.Appearance.Fill.ColorMirror = clNone
    Status.Appearance.Fill.ColorMirrorTo = clNone
    Status.Appearance.Fill.GradientType = gtSolid
    Status.Appearance.Fill.GradientMirrorType = gtSolid
    Status.Appearance.Fill.BorderColor = clGray
    Status.Appearance.Fill.Rounding = 0
    Status.Appearance.Fill.ShadowOffset = 0
    Status.Appearance.Fill.Glow = gmNone
    Status.Appearance.Font.Charset = DEFAULT_CHARSET
    Status.Appearance.Font.Color = clWhite
    Status.Appearance.Font.Height = -11
    Status.Appearance.Font.Name = 'Tahoma'
    Status.Appearance.Font.Style = []
    Caption = 'Close USB Device'
    Color = 15784647
    TabOrder = 2
    Version = '2.0.2.0'
    OnClick = AdvSmoothButton3Click
  end
  object StatusBar1: TStatusBar
    Left = 0
    Top = 296
    Width = 419
    Height = 19
    Panels = <
      item
        Text = 'Jalur USB tertutup'
        Width = 300
      end
      item
        Text = 'by semarme.com'
        Width = 50
      end>
  end
end
